### ISSUE TITLE
* Unknown configuration section 'dnsmasq'.

### ISSUE THREAD

**Issue by codezninja** [mattes/vagrant-dnsmasq#18]
I'm having issue getting this working right now. I'm getting the following error.

``` code
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.
```

In my Vagrantfile I added this to the top to make sure that the plugin is installed.

``` code
unless Vagrant.has_plugin?("vagrant-dnsmasq")
  raise 'some-plugin is not installed!'
end
```

 Any thoughts on how to debug this issue?

**Comment by codezninja** [comment]
here's the output i get when tryign to run the tests vagrant

``` bash
[ezjacob@Ezbons-MacBook-Air:~/.vagrant.d/gems/gems/vagrant-dnsmasq-0.1.1/test]
[01:05:31] 1 $ VAGRANT_LOG=INFO vagrant up
 INFO global: Vagrant version: 1.7.2
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant"
 INFO global: VAGRANT_LOG="INFO"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/bin/../embedded"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_DETECTED_OS="Darwin"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: Plugins:
 INFO global:   - bundler = 1.7.11
 INFO global:   - json = 1.8.2
 INFO global:   - mime-types = 1.25.1
 INFO global:   - rdoc = 4.2.0
 INFO global:   - rest-client = 1.6.8
 INFO global:   - vagrant-dnsmasq = 0.1.1
 INFO global:   - vagrant-share = 1.1.3
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: global-status command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: help command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: list-commands command
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: push command
 INFO manager: Registered plugin: rdp command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: version command
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: winrm communicator
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: CoreOS guest
 INFO manager: Registered plugin: Darwin guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: ESXi guest.
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: Funtoo guest
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: Mint guest
 INFO manager: Registered plugin: NetBSD guest
 INFO manager: Registered plugin: NixOS guest
 INFO manager: Registered plugin: OmniOS guest.
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: RedHat guest
 INFO manager: Registered plugin: SmartOS guest.
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: Solaris 11 guest.
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: TinyCore Linux guest.
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Windows guest.
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Mac OS X host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: null host
 INFO manager: Registered plugin: Red Hat host
 INFO manager: Registered plugin: Slackware host
 INFO manager: Registered plugin: SUSE host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: docker-provider
 INFO manager: Registered plugin: Hyper-V provider
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: ansible
 INFO manager: Registered plugin: CFEngine Provisioner
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: docker
 INFO manager: Registered plugin: file
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: salt
 INFO manager: Registered plugin: shell
 INFO manager: Registered plugin: atlas
 INFO manager: Registered plugin: ftp
 INFO manager: Registered plugin: heroku
 INFO manager: Registered plugin: local-exec
 INFO manager: Registered plugin: noop
 INFO manager: Registered plugin: NFS synced folders
 INFO manager: Registered plugin: RSync synced folders
 INFO manager: Registered plugin: SMB synced folders
 INFO global: Loading plugins!
 INFO manager: Registered plugin: vagrant-share
 INFO vagrant: `vagrant` invoked: ["up"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x000001008a4340>)
 INFO environment:   - cwd: /Users/ezjacob/.vagrant.d/gems/gems/vagrant-dnsmasq-0.1.1/test
 INFO environment: Home path: /Users/ezjacob/.vagrant.d
 INFO environment: Local data path: /Users/ezjacob/.vagrant.d/gems/gems/vagrant-dnsmasq-0.1.1/test/.vagrant
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000001012203b0>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000001012fa8f8>
 INFO cli: CLI: [] "up" []
 INFO loader: Set :root = #<Pathname:/Users/ezjacob/.vagrant.d/gems/gems/vagrant-dnsmasq-0.1.1/test/Vagrantfile>
 INFO loader: Loading configuration in order: [:home, :root]
 INFO loader: Set "2165056780_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "2165056780_machine_default"]
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
 INFO base: VBoxManage path: VBoxManage
 INFO environment: Getting machine: default (virtualbox)
 INFO environment: Uncached load of machine.
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
 INFO base: VBoxManage path: VBoxManage
 INFO loader: Set "2165056780_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "2165056780_machine_default"]
 INFO box_collection: Box found: precise64 (virtualbox)
 INFO loader: Set :"2158009940_precise64_virtualbox" = #<Pathname:/Users/ezjacob/.vagrant.d/boxes/precise64/0/virtualbox/Vagrantfile>
 INFO loader: Loading configuration in order: [:"2158009940_precise64_virtualbox", :home, :root, "2165056780_machine_default"]
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: VagrantPlugins::ProviderVirtualBox::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x000001021761e8>
 INFO machine:   - Data dir: /Users/ezjacob/.vagrant.d/gems/gems/vagrant-dnsmasq-0.1.1/test/.vagrant/machines/default/virtualbox
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
 INFO base: VBoxManage path: VBoxManage
 INFO machine: New machine ID: nil
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
 INFO base: VBoxManage path: VBoxManage
 INFO command: With machine: default (#<VagrantPlugins::ProviderVirtualBox::Provider:0x00000102166b08 @logger=#<Log4r::Logger:0x00000102166a68 @fullname="vagrant::provider::virtualbox", @outputters=[], @additive=true, @name="virtualbox", @path="vagrant::provider", @parent=#<Log4r::Logger:0x00000101460288 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x000001021dc060 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000001021d7f88>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000001021d48b0 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x000001022040b0 @level=0, @outputters=[]>, @level=2, @trace=false>, @level=2, @trace=false>, @machine=#<Vagrant::Machine: default (VagrantPlugins::ProviderVirtualBox::Provider)>, @driver=#<VagrantPlugins::ProviderVirtualBox::Driver::Meta:0x000001013bb940 @logger=#<Log4r::Logger:0x0000010210e9d0 @fullname="vagrant::provider::virtualbox::meta", @outputters=[], @additive=true, @name="meta", @path="vagrant::provider::virtualbox", @parent=#<Log4r::Logger:0x00000102166a68 @fullname="vagrant::provider::virtualbox", @outputters=[], @additive=true, @name="virtualbox", @path="vagrant::provider", @parent=#<Log4r::Logger:0x00000101460288 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x000001021dc060 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000001021d7f88>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000001021d48b0 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x000001022040b0 @level=0, @outputters=[]>, @level=2, @trace=false>, @level=2, @trace=false>, @level=2, @trace=false>, @interrupted=false, @vboxmanage_path="VBoxManage", @uuid=nil, @version="4.3.20", @driver=#<VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3:0x00000101342310 @logger=#<Log4r::Logger:0x0000010085ef98 @fullname="vagrant::provider::virtualbox_4_3", @outputters=[], @additive=true, @name="virtualbox_4_3", @path="vagrant::provider", @parent=#<Log4r::Logger:0x00000101460288 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x000001021dc060 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000001021d7f88>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000001021d48b0 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x000001022040b0 @level=0, @outputters=[]>, @level=2, @trace=false>, @level=2, @trace=false>, @interrupted=false, @vboxmanage_path="VBoxManage", @uuid=nil>>, @cap_logger=#<Log4r::Logger:0x000001021fee08 @fullname="vagrant::capability_host::vagrantplugins::providervirtualbox::provider", @outputters=[], @additive=true, @name="provider", @path="vagrant::capability_host::vagrantplugins::providervirtualbox", @parent=#<Log4r::Logger:0x00000101460288 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x000001021dc060 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000001021d7f88>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000001021d48b0 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x000001022040b0 @level=0, @outputters=[]>, @level=2, @trace=false>, @level=2, @trace=false>, @cap_host_chain=[[:virtualbox, #<#<Class:0x000001021ff6f0>:0x000001021bdb38>]], @cap_args=[#<Vagrant::Machine: default (VagrantPlugins::ProviderVirtualBox::Provider)>], @cap_caps={:docker=>#<Vagrant::Registry:0x000001021ff3a8 @items={:public_address=>#<Proc:0x000001013c9900@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/plugin.rb:54>, :proxy_machine=>#<Proc:0x000001013c97e8@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/plugin.rb:59>}, @results_cache={}>, :hyperv=>#<Vagrant::Registry:0x000001021ff290 @items={:public_address=>#<Proc:0x000001021ee080@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/hyperv/plugin.rb:25>}, @results_cache={}>, :virtualbox=>#<Vagrant::Registry:0x000001021ff0d8 @items={:forwarded_ports=>#<Proc:0x0000010215d5f8@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/plugin.rb:27>, :nic_mac_addresses=>#<Proc:0x0000010215d558@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/plugin.rb:32>, :public_address=>#<Proc:0x000001014416a8@/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.3/lib/vagrant-share.rb:39>}, @results_cache={}>}>)
 INFO interface: info: Bringing machine 'default' up with 'virtualbox' provider...
Bringing machine 'default' up with 'virtualbox' provider...
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because provider doesn't support it: virtualbox
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x0000010285e898> up {:destroy_on_error=>true, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil}
 INFO machine: Calling action: up on provider VirtualBox (new VM)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-eeb40432e2089437bb34bd9e07820fae
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /Users/ezjacob/.vagrant.d/gems/gems/vagrant-dnsmasq-0.1.1/test>]
 INFO host: Detected: darwin!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000001008ed748>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckVirtualbox:0x00000101320d50>
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "list", "hostonlyifs"]
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x00000101320cb0>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000001022348a0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x0000010223f200>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x0000010223f200>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Warden:0x00000102214280>
 INFO warden: Calling IN action: #<Proc:0x000001014334e0@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleBox:0x000001022141e0>
 INFO handle_box: Machine already has box. HandleBox will not run.
 INFO warden: Calling IN action: #<Proc:0x000001021dd6b8@/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000101320c38>
ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.


 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000101320cb0>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.


 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.


 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-eeb40432e2089437bb34bd9e07820fae
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000001014012d8>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::ConfigInvalid: There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.

>
ERROR vagrant: There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.


ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:18:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.


There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'dnsmasq'.


 INFO interface: Machine: error-exit ["Vagrant::Errors::ConfigInvalid", "There are errors in the configuration of this machine. Please fix\nthe following errors and try again:\n\nVagrant:\n* Unknown configuration section 'dnsmasq'.\n\n"]

[ezjacob@Ezbons-MacBook-Air:~/.vagrant.d/gems/gems/vagrant-dnsmasq-0.1.1/test]
[14:57:15] 1 $
```

**Comment by mattes** [comment]
Can you post your according Vagrantfile?

**Comment by codezninja** [comment]
So looks like vagrant doesn't look at my gem paths for the vagrant-dnsmasq. I had to install likeso

``` bash
sudo gem install --install-dir=/opt/vagrant/embedded/gems vagrant-dnsmasq
```
