### ISSUE TITLE
Release 0.1.2

### ISSUE THREAD

**Issue by nickhammond** [mattes/vagrant-dnsmasq#19]
There's some commits that fix the ffi dependency resolution messages/errors that are present in 0.1.1 which is the version currently available on rubygems, specifically 2826b914f1b2303ece9a97257e077cbb9cd29c0f

``` shell
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find ffi-1.9.8 in any of the sources (Bundler::GemNotFound)
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:85:in `map!'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:85:in `materialize'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:166:in `requested_specs'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/environment.rb:18:in `requested_specs'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:13:in `setup'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler.rb:122:in `setup'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/setup.rb:17:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by dlbewley** [comment]
still see vagrant errors after a `sudo gem install ffi`

```
$ gem list ffi

*** LOCAL GEMS ***

ffi (1.9.10, 1.9.8)
```

```
$ vagrant ssh master
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find ffi-1.9.10 in any of the sources (Bundler::GemNotFound)
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:85:in `map!'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:85:in `materialize'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:166:in `requested_specs'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/environment.rb:18:in `requested_specs'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:13:in `setup'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler.rb:122:in `setup'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/setup.rb:17:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/custom_require.rb:36:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/custom_require.rb:36:in `require'
```

**Comment by nickhammond** [comment]
@dlbewley `v0.1.2` hasn't been released yet https://rubygems.org/gems/vagrant-dnsmasq

The only workaround currently is installing the plugin via a locally installed version of it, [similar to here](http://stackoverflow.com/questions/17028132/vagrant-install-plugin-from-github).
